services:
  elementary:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8012:5000"
    environment:
      - JAIL_ENV_FLAG=DEVSTORM{OrCZepbroR@^5Z^F}
      - JAIL_MEM=20M
      - JAIL_ENV_PYTHONUNBUFFERED=1
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /var/log
